grpc:
  host: 0.0.0.0
  port: 6000

gateway:
  host: 0.0.0.0
  port: 6002

swagger:
  host: 0.0.0.0
  port: 6001
  dist: "swagger/dist/"
  filepath: "swagger/api/to_do_service/to_do_service.swagger.json"

db:
  DSN: "postgres://nikita:qwerty1234@localhost:5432/nikita"
  DSND: "postgres://nikita:qwerty1234@db:5432/nikita"
  maxOpenConns: 5
  maxIdleConns: 5
  connMaxIdleTime: 5m
  connMaxLifetime: 5m